#!/usr/bin/with-contenv bash

if [ -z "$BASE_DN" ]; then
    BASE_DN="dc="$( echo $DOMAIN | sed -e "s/\./,dc=/g" )
    ROOT=$( echo $DOMAIN | cut -d '.' -f1 )
fi

cp /etc/openldap/template/ldap.conf /etc/openldap/ldap.conf

sed -i "s;{BASE_DN};$BASE_DN;g" /etc/openldap/ldap.conf
sed -i "s;{ADMIN_PASS};$ADMIN_PASS;g" /etc/openldap/ldap.conf

chmod 0600 /etc/openldap/ldap.conf
chown ldap:ldap /etc/openldap/ldap.conf
