#!/usr/bin/with-contenv bash

if [ -z "$BASE_DN" ]; then
    BASE_DN="dc="$( echo $DOMAIN | sed -e "s/\./,dc=/g" )
    ROOT=$( echo $DOMAIN | cut -d '.' -f1 )
fi

cp /etc/template/ldap.conf /etc/openldap/ldap.conf

sed -i "s;{BASE_DN};$BASE_DN;g" /etc/openldap/ldap.conf
sed -i "s;{ADMIN_PASS};$ADMIN_PASS;g" /etc/openldap/ldap.conf

chmod 0600 /etc/openldap/ldap.conf
chown ldap:ldap /etc/openldap/ldap.conf

sed -i "s;{ADMIN_PASS};$ADMIN_PASS;g" /etc/fusiondirectory/fusiondirectory.conf
sed -i "s;{BASE_DN};$BASE_DN;g" /etc/fusiondirectory/fusiondirectory.conf
sed -i "s;{INSTANCE};$INSTANCE;g" /etc/fusiondirectory/fusiondirectory.conf

chmod 640 /etc/fusiondirectory/fusiondirectory.conf
chown root:nginx /etc/fusiondirectory/fusiondirectory.conf

chown -R ldap:ldap /var/lib/openldap
chown -R ldap:ldap /etc/openldap
chown -R ldap:ldap /run/openldap
chown -R nginx:nginx /var/www/fusiondirectory/html 

chmod 777 /tmp

mkdir -p /tmp/state
touch /tmp/state/10-openldap-init
