#!/usr/bin/with-contenv bash

if [ -z "$BASE_DN" ]; then
    BASE_DN="dc="$( echo $DOMAIN | sed -e "s/\./,dc=/g" )
    ROOT=$( echo $DOMAIN | cut -d '.' -f1 )
fi

  sed -i "s;{ADMIN_PASS};$ADMIN_PASS;g" /etc/fusiondirectory/fusiondirectory.conf
  sed -i "s;{BASE_DN};$BASE_DN;g" /etc/fusiondirectory/fusiondirectory.conf
  sed -i "s;{INSTANCE};$INSTANCE;g" /etc/fusiondirectory/fusiondirectory.conf

  sed -i "s;{SMTP_HOST};$SMTP_HOST;g" /etc/msmtprc
  sed -i "s;{SMTP_PORT};$SMTP_PORT;g" /etc/msmtprc
  sed -i "s;{SMTP_AUTH};$SMTP_AUTH;g" /etc/msmtprc
  sed -i "s;{SMTP_TLS};$SMTP_TLS;g" /etc/msmtprc
  sed -i "s;{SMTP_USER};$SMTP_USER;g" /etc/msmtprc
  sed -i "s;{SMTP_PASS};$SMTP_PASS;g" /etc/msmtprc
  sed -i "s;{SMTP_FROM};$SMTP_FROM;g" /etc/msmtprc


  chmod 640 /etc/fusiondirectory/fusiondirectory.conf
  chown root:nginx /etc/fusiondirectory/fusiondirectory.conf