#!/usr/bin/with-contenv bash

chown -R ldap:ldap /var/lib/openldap
chown -R ldap:ldap /etc/openldap
chown -R ldap:ldap /run/openldap
chown -R nginx:nginx /var/www/fusiondirectory/html 

chmod 777 /tmp
echo "0" > /tmp/openldap-init
